### ISSUE TITLE
Ｑｏｓ

### ISSUE THREAD

**Issue by chenwu-cc** [PepperlFuchs/pf_lidar_ros_driver#117] opened 2023-05-16 07:25 UTC
New subscription discovered on topic '/scan', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY

ｈｏｗ　ｔｏ　ｓｏｌｖｅ　ｉｔ

**Comment by ipa-hsd** [comment] 2023-05-23 16:16
I am assuming the issue is fixed so closing it for now. If you still facing issues, feel free to reopen.

**Closed by ipa-hsd** 2023-05-23 16:16 UTC
