### ISSUE TITLE
unable to locate:  pf_driver/PFDriverR2000Config.h and pf_driver/PFDriverR2300Config.h

### ISSUE THREAD

**Issue by hd-n** [PepperlFuchs/pf_lidar_ros_driver#100] opened 2022-12-09 12:27 UTC
I am trying to compile and use the library for a measurement application (not with ROS, but independent logic). 
but facing issue in compilation.

where can i find the file?
![image](https://user-images.githubusercontent.com/91519331/206702369-d81fa2c7-52a9-4a89-8c44-766741618a16.png)

**Comment by ipa-hsd** [comment] 2022-12-14 10:13
These files are built from the dynamic reconfigure config files: https://github.com/PepperlFuchs/pf_lidar_ros_driver/tree/main/pf_driver/cfg.

Once the package is built, you can find it in the install space.

**Comment by ipa-hsd** [comment] 2023-01-23 13:22
@hd-n I will close the issue. Feel free to re-open if the issue is still not solved.

**Closed by ipa-hsd** 2023-01-23 13:22 UTC
